### ISSUE TITLE
Duplicate Lines in Export

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#46]
There are a couple cases in the May30-Jun16 pay period where there were duplicate entries in the export file.

There is one commonality that I noticed.  The pay entries in both cases have multiple spellings of the individual
This is from GP:
![image](https://user-images.githubusercontent.com/10456426/123459361-6b35b700-d5a3-11eb-9b8b-85beb56d473c.png)
![image](https://user-images.githubusercontent.com/10456426/123459472-8d2f3980-d5a3-11eb-948b-d06fe7e06b21.png)

This example is from Edmonton:
![image](https://user-images.githubusercontent.com/10456426/123463487-d0d87200-d5a8-11eb-90c0-c54ae3d0b936.png)
![image](https://user-images.githubusercontent.com/10456426/123459565-b18b1600-d5a3-11eb-83a8-85975b96431b.png)

Viktor also mentioned a cause for this the other day. I belive it happens when employees are not selected in eService, but they only type the name in.

Lets hop on a call on Tuesday and discuss options for fixing this issue.

**Comment by vikmol** [comment]
It looks there are two parts of the issue:
1. Non-consistent using of Preferred Name for building Full Employee Name (EmployeeName) - eService and Reference data use Preferred Name as a First Name if exists, while Work Assignments use only First Name ignoring Preferred Name. So, automated records end up in Pay Entries with First Name while manually entered have Preferred name instead.
2. Aggregation in the app is done, it seems, by EmployeeName (which might differ because of the above) instead of EmployeeId which is the same in both cases.

In order to fix the issue we need to update WorkAssignment API logic to accommodate Preferred Name for building Full Name.
Also, it would be safer to have the app aggregation done by EmployeeId instead of EmployeeName.

**Comment by GarrickConvverge** [comment]
The Export should now be fixed, on the flow side.
