### ISSUE TITLE
Error saving when testing latest udpates

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#50]
All changes for the next release seem to work good except I'm getting an error when saving a pay entry.
![image](https://user-images.githubusercontent.com/10456426/128385995-4dbbcae5-dbf8-408a-970e-a701c02b6e0f.png)

**Comment by GarrickConvverge** [comment]
Hi Chris, so this looks like its because the pay period summary item does not exist in the share point list, should all default pay period summaries be synced from the sql database and pay entries get locked out until a pay period summary item is created, or should a new default pay period summary item be created when a pay entry is created?

**Comment by cgaine** [comment]
No worries, It seems the script to auto populate this in the dev environment was stopped. Viktor has enabled the script... Thanks
